---
title: "Tidy modelling "
author: "Matteo Sostero"
output: github_document
editor_options: 
  chunk_output_type: console
---


## Packages for this session

|    package    |          purpose           | installation |
| ------------- | -------------------------- | ------------ |
| *tidyverse*   | everything                 | CRAN         |
| *nycflight13* | example datasets           | CRAN         |
| *broom*       | tidying statistical models | CRAN         |


If not yet installed, download packages with `install.packages("name")`.
If asked, **do not compile from source**.
```{r eval=FALSE, message=FALSE, include=FALSE}
install.packages("broom")
```

Load the packages for the session:
```{r}
# *tidyverse* loads the core packages of the *tidyverse* and shows their version.
library(tidyverse)
library(nycflights13)
library(broom)
```


## Model evaluation and tidying

```{r}
data(flights)

flights %>%
  split(.$month) %>%
  set_names(month.name) %>%
  map(~ lm(dep_delay ~ dep_time + day, data = .)) %>%
  map_dfr(~ tidy(.), .id = "chunk")
```

